//
//  DeveloperPreview.swift
//  SwiftUI-Airbnb
//
//  Created by Umut Yenidil on 3.09.2024.
//

import Foundation

class DeveloperPreview {
    static let shared = DeveloperPreview()
    
    var listings: [Listing] = [
        Listing(
                    id: UUID(),
                    ownerUid: UUID(),
                    ownerName: "John Doe",
                    ownerImageUrl: "https://picsum.photos/200/300",
                    bedroomCount: 2,
                    bathroomCount: 1,
                    guestCount: 4,
                    bedCount: 2,
                    pricePerNight: 120,
                    lat: 37.7749,
                    lng: -122.4194,
                    imageURLs: ["https://picsum.photos/300/200", "https://picsum.photos/300/201", "https://picsum.photos/300/202"],
                    address: "123 Main St",
                    city: "San Francisco",
                    state: "CA",
                    type: ListingType.apartment,
                    title: "Cozy Apartment in",
                    rating: 4.8,
                    features: [.selfCheckIn, .superHost],
                    amenities: [.wifi, .kitchen, .laundry, .tv]
                ),
                Listing(
                    id: UUID(),
                    ownerUid: UUID(),
                    ownerName: "Jane Smith",
                    ownerImageUrl: "https://picsum.photos/200/301",
                    bedroomCount: 3,
                    bathroomCount: 2,
                    guestCount: 6,
                    bedCount: 3,
                    pricePerNight: 200,
                    lat: 34.0522,
                    lng: -118.2437,
                    imageURLs: ["https://picsum.photos/300/203", "https://picsum.photos/300/204", "https://picsum.photos/300/205"],
                    address: "456 Elm St",
                    city: "Los Angeles",
                    state: "CA",
                    type: ListingType.apartment,
                    title: "Modern House in LA",
                    rating: 4.9,
                    features: [.selfCheckIn, .superHost],
                    amenities: [.pool, .wifi, .kitchen, .balcony, .tv]
                ),
                Listing(
                    id: UUID(),
                    ownerUid: UUID(),
                    ownerName: "Alice Johnson",
                    ownerImageUrl: "https://picsum.photos/200/302",
                    bedroomCount: 1,
                    bathroomCount: 1,
                    guestCount: 2,
                    bedCount: 1,
                    pricePerNight: 80,
                    lat: 40.7128,
                    lng: -74.0060,
                    imageURLs: ["https://picsum.photos/300/206", "https://picsum.photos/300/207", "https://picsum.photos/300/208"],
                    address: "789 Pine St",
                    city: "New York",
                    state: "NY",
                    type: ListingType.apartment,
                    title: "Chic Studio in NYC",
                    rating: 4.7,
                    features: [.selfCheckIn],
                    amenities: [.wifi, .kitchen, .laundry]
                ),
                Listing(
                    id: UUID(),
                    ownerUid: UUID(),
                    ownerName: "Michael Brown",
                    ownerImageUrl: "https://picsum.photos/200/303",
                    bedroomCount: 4,
                    bathroomCount: 3,
                    guestCount: 8,
                    bedCount: 4,
                    pricePerNight: 350,
                    lat: 51.5074,
                    lng: -0.1278,
                    imageURLs: ["https://picsum.photos/300/209", "https://picsum.photos/300/210", "https://picsum.photos/300/211"],
                    address: "1010 Abbey Rd",
                    city: "London",
                    
                    state: "England",
                    type: ListingType.apartment,
                    title: "Luxurious Villa in London",
                    rating: 5.0,
                    features: [.superHost],
                    amenities: [.pool, .wifi, .kitchen, .office, .alarmSystem, .tv]
                ),
                Listing(
                    id: UUID(),
                    ownerUid: UUID(),
                    ownerName: "Sophia Williams",
                    ownerImageUrl: "https://picsum.photos/200/304",
                    bedroomCount: 2,
                    bathroomCount: 2,
                    guestCount: 5,
                    bedCount: 2,
                    pricePerNight: 150,
                    lat: 48.8566,
                    lng: 2.3522,
                    imageURLs: ["https://picsum.photos/300/212", "https://picsum.photos/300/213", "https://picsum.photos/300/214"],
                    address: "15 Rue de Rivoli",
                    city: "Paris",
                    state: "Île-de-France",
                    type: ListingType.apartment,
                    title: "Romantic Apartment in Paris",
                    rating: 4.6,
                    features: [.selfCheckIn],
                    amenities: [.wifi, .kitchen, .balcony]
                ),
                Listing(
                    id: UUID(),
                    ownerUid: UUID(),
                    ownerName: "David Lee",
                    ownerImageUrl: "https://picsum.photos/200/305",
                    bedroomCount: 5,
                    bathroomCount: 4,
                    guestCount: 10,
                    bedCount: 5,
                    pricePerNight: 400,
                    lat: 35.6895,
                    lng: 139.6917,
                    imageURLs: ["https://picsum.photos/300/215", "https://picsum.photos/300/216", "https://picsum.photos/300/217"],
                    address: "123 Tokyo Rd",
                    city: "Tokyo",
                    state: "Tokyo",
                    type: ListingType.apartment,
                    title: "Spacious House in Tokyo",
                    rating: 4.9,
                    features: [.superHost],
                    amenities: [.wifi, .kitchen, .office, .laundry, .tv]
                ),
                Listing(
                    id: UUID(),
                    ownerUid: UUID(),
                    ownerName: "Emily Davis",
                    ownerImageUrl: "https://picsum.photos/200/306",
                    bedroomCount: 3,
                    bathroomCount: 2,
                    guestCount: 6,
                    bedCount: 3,
                    pricePerNight: 180,
                    lat: 41.9028,
                    lng: 12.4964,
                    imageURLs: ["https://picsum.photos/300/218", "https://picsum.photos/300/219", "https://picsum.photos/300/220"],
                    address: "456 Rome St",
                    city: "Rome",
                    state: "Lazio",
                    type: ListingType.apartment,
                    title: "Charming Apartment in Rome",
                    rating: 4.7,
                    features: [.selfCheckIn],
                    amenities: [.wifi, .kitchen, .balcony]
                ),
                Listing(
                    id: UUID(),
                    ownerUid: UUID(),
                    ownerName: "James Wilson",
                    ownerImageUrl: "https://picsum.photos/200/307",
                    bedroomCount: 2,
                    bathroomCount: 2,
                    guestCount: 4,
                    bedCount: 2,
                    pricePerNight: 160,
                    lat: 39.9042,
                    lng: 116.4074,
                    imageURLs: ["https://picsum.photos/300/221", "https://picsum.photos/300/222", "https://picsum.photos/300/223"],
                    address: "789 Beijing St",
                    city: "Beijing",
                    state: "Beijing",
                    type: ListingType.apartment,
                    title: "Modern Apartment in Beijing",
                    rating: 4.8,
                    features: [.superHost],
                    amenities: [.wifi, .kitchen, .tv, .laundry]
                ),
                Listing(
                    id: UUID(),
                    ownerUid: UUID(),
                    ownerName: "Olivia Martinez",
                    ownerImageUrl: "https://picsum.photos/200/308",
                    bedroomCount: 4,
                    bathroomCount: 3,
                    guestCount: 8,
                    bedCount: 4,
                    pricePerNight: 300,
                    lat: -33.8688,
                    lng: 151.2093,
                    imageURLs: ["https://picsum.photos/300/224", "https://picsum.photos/300/225", "https://picsum.photos/300/226"],
                    address: "1010 Sydney Rd",
                    city: "Sydney",
                    state: "NSW",
                    type: ListingType.apartment,
                    title: "Luxurious House in Sydney",
                    rating: 4.9,
                    features: [.superHost],
                    amenities: [.pool, .wifi, .kitchen, .balcony, .tv]
                ),
                Listing(
                    id: UUID(),
                    ownerUid: UUID(),
                    ownerName: "William Garcia",
                    ownerImageUrl: "https://picsum.photos/200/309",
                    bedroomCount: 3,
                    bathroomCount: 2,
                    guestCount: 6,
                    bedCount: 3,
                    pricePerNight: 220,
                    lat: 37.7749,
                    lng: -122.4194,
                    imageURLs: ["https://picsum.photos/300/227", "https://picsum.photos/300/228", "https://picsum.photos/300/229"],
                    address: "123 Market St",
                    city: "San Francisco",
                
                    state: "CA",
                    type: ListingType.apartment,
                    title: "Beautiful House in San Francisco",
                    rating: 4.7,
                    features: [.selfCheckIn],
                    amenities: [.wifi, .kitchen, .tv, .office]
                )
    ]
}
